name: refresh-data
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '23 2 * * 1' # runs every Monday at 2:23

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Initialize python env
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pygithub python-gitlab beautifulsoup4 lxml
      - name: Create new export
        run: |
          python lpa_table_export.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      - name: Create new template
        run: |
          python lpa_html_builder.py
      - name: Pull Remote Changes
        run: git pull
      - uses: stefanzweifel/git-auto-commit-action@v4
